name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/setup-java-jdk#publishing-using-apache-maven
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Build (and publish to Sonatype OSSRH when on master)
        run: |
          # only use -P release when (1) on master branch, (2) no pull request
          if [ ${GITHUB_REF#refs/heads/} == "master" ]; then MAVEN_PROFILE="-P release"; fi
          mvn -V -B clean deploy $MAVEN_PROFILE
        env:
          OSSRH_USERNAME: qqilihq
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - uses: codecov/codecov-action@v1
        with:
          file: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: true

      # TODO parse surefire reports
